name: omeg_bazaar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_svg: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.4.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.7.2
  flutter_dotenv: ^5.1.0
  timeline_tile: ^2.0.0
  provider: ^6.0.5
  razorpay_flutter: ^1.4.0
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ====== CORRECT PLACEMENT ====== #
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/omeglogo.png"
# =============================== #

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf